### ISSUE TITLE
Can't attack mob

### ISSUE THREAD

**Issue by wibucter** [sylvxa/petprotect#1]
Can't attack mobs like zombies, spider,...
Log:
```
[13:51:30 ERROR]: Failed to handle packet net.minecraft.class_2824@14c48115, suppressing error
java.lang.NullPointerException: Cannot invoke "lol.sylvie.petprotect.config.ConfigInstance.shouldIgnoreCreative()" because "lol.sylvie.petprotect.PetProtect.config" is null
	at knot/lol.sylvie.petprotect.PetProtect.lambda$onInitialize$0(PetProtect.java:25) ~[petprotect-1.1.jar:?]
	at knot/net.fabricmc.fabric.api.event.player.AttackEntityCallback.lambda$static$0(AttackEntityCallback.java:44) ~[fabric-events-interaction-v0-0.7+ba9dae0619-32d1bbc394783851.jar:?]
	at knot/net.minecraft.class_3222.handler$zih000$fabric-events-interaction-v0$onPlayerInteractEntity(class_3222.java:4138) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3222.method_7324(class_3222.java) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244$1.method_34218(class_3244.java:1650) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824$1.method_34213(class_2824.java:174) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824.method_34209(class_2824.java:74) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_12062(class_3244.java:1610) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824.method_12251(class_2824.java:61) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824.method_11054(class_2824.java:15) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[13:51:31 INFO]: wibucter was slain by Spider
```

**Comment by sylvxa** [comment]
hi there! my first guess is that your configuration file corrupted. can you stop the server, delete `config/petprotect.json`, and then see if the issue persists?
